### ISSUE TITLE
WARNING: SSL issue - the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by andres-k** [MoebiusSolutions/cac-agent#23]
Hey, i'm trying to run this on macos 10.14. I followed the getting started guide, but when I bring up the cac-ssl-relay it blurps out an error once I request anything. Only difference from the guide is I'm binding to localhost instead of something I specified in /etc/hosts because binding against `127.0.0.5 service-local` failed. 

Same errors with both cac-ssl-relay-1.13-jar-with-dependencies.jar and cac-ssl-relay-1.12-jar-with-dependencies.jar. Tried building from source and yeah, still the same error. 

Here's the stacktrace. 
```
Loading properties from /Users/bob/.moesol/cac-agent/agent.properties
Using trustore /Users/bob/.moesol/cac-agent/truststore.jks
Linux key manager
entry: localhost:9050=mydomain.com:443
all started

Exception in thread "relay-io: Socket[addr=/127.0.0.1,port=60097,localport=9050] to com.moesol.cac.relay.BiDirectionalRelay$RepairableSocket@4cad0dd" java.lang.RuntimeException: java.net.SocketException: Connection or outbound has closed
	at com.moesol.cac.relay.BiDirectionalRelay.copyFromClient(BiDirectionalRelay.java:121)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketException: Connection or outbound has closed
	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:975)
	at com.moesol.cac.relay.BiDirectionalRelay.copyFromClientWithOneTimeRetry(BiDirectionalRelay.java:149)
	at com.moesol.cac.relay.BiDirectionalRelay.copyFromClient(BiDirectionalRelay.java:115)
	... 1 more
Mar 26, 2020 4:57:18 PM com.moesol.cac.relay.BiDirectionalRelay copyFromServerWithOneTimeReconnect
INFO: One-time read retry
Mar 26, 2020 4:57:18 PM com.moesol.cac.relay.BiDirectionalRelay copyFromServerWithOneTimeReconnect
WARNING: SSL issue
javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1313)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:408)
	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:716)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:799)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at com.moesol.cac.relay.BiDirectionalRelay.copyFromServerWithOneTimeReconnect(BiDirectionalRelay.java:184)
	at com.moesol.cac.relay.BiDirectionalRelay.copyFromServer(BiDirectionalRelay.java:128)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:102)
	at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
	at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:300)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:176)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:189)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1316)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1207)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1150)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:177)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1151)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1062)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	... 6 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:99)
	... 22 more
```

**Comment by moesol** [comment]
Either the file - /Users/bob/.moesol/cac-agent/truststore.jks is missing, empty, or does not contain the root certs for the site you are trying to hit.

**Comment by andres-k** [comment]
Yep that was it. For whatever reason certs saved off from firefox hicked up. Using openssl to catch the cert did the trick. 

Sorry for bothering you with this, thanks for the tool! 

```bash 
echo | openssl s_client -servername ${servername} -connect ${hostandport} | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ouptut.crt
```

**Comment by moesol** [comment]
Awesome. Glad you are getting use out of the project.
